#!/bin/bash
# Session Summary Hook - 会话结束时自动生成摘要
# 在Claude完成响应后触发

set -e

# 创建会话日志目录
SESSIONS_DIR="$HOME/.claude/sessions"
mkdir -p "$SESSIONS_DIR"

# 生成时间戳
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="$SESSIONS_DIR/session-$TIMESTAMP.log"

# 记录会话基本信息
cat > "$LOG_FILE" <<EOF
# Claude Code Session Summary

**Time**: $(date '+%Y-%m-%d %H:%M:%S')
**Duration**: [To be tracked]
**Working Directory**: $(pwd)

## Session Metadata
- Session ID: $TIMESTAMP
- User: $USER
- Host: $(hostname)

## Notes
Session ended. Full context available in conversation history.

---
Generated by Hooks mechanism
EOF

# 清理旧日志（保留最近30天）
find "$SESSIONS_DIR" -name "session-*.log" -mtime +30 -delete 2>/dev/null || true

# 输出简短通知到stderr（会显示给用户）
echo "📊 Session logged: $LOG_FILE" >&2

exit 0
